on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get private repo with action
        uses: actions/checkout@v2
        with:
          repository: canhdh/github-action-example
          ref: v1.0.1
          token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
          path: .github/actions/externals
      - run: ls .github/actions/
      - run: ls ./.github/actions/externals
      - id: foo
        uses: ./.github/actions/externals/action.yaml
        with:
          who-to-greet: "Canh DH"
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
